import dayjs from "dayjs";

// types
import { Schedule } from "types/schedule";

export const schedulesMock: Array<Schedule> = [
  {
    id: 1,
    datetime: dayjs(),
    realStartDatetime: null,
    client: {
      id: 1,
      fullname: 'Joséfa da Silva',
      phoneNumber: '11994224242',
      createdAt: dayjs(),
      updatedAt: null,
      deletedAt: null,
    },
    procedure: {
      id: 1,
      name: 'Extensão de cílios',
      priceInCents: 10000,
    },
    discountPercent: null,
    coupon: { 
      id: 1,
      name: 'Combo',
      percent: 15,
      isActive: true,
      createdAt: dayjs(),
      updatedAt: null,
      deletedAt: null,
    },
    isConfirmed: true,
    isCancelled: false,
    isNoShow: false,
    isRescheduled: false,
    createdAt: dayjs(),
    updatedAt: null,
    deletedAt: null,
  },
  {
    id: 2,
    datetime: dayjs(),
    realStartDatetime: null,
    client: {
      id: 2,
      fullname: 'Maria de Souza',
      phoneNumber: '11975429866',
      createdAt: dayjs(),
      updatedAt: null,
      deletedAt: null,
    },
    procedure: {
      id: 2,
      name: 'Lifting',
      priceInCents: 8000,
    },
    discountPercent: 10,
    coupon: { 
      id: 1,
      name: 'Combo',
      percent: 15,
      isActive: true,
      createdAt: dayjs(),
      updatedAt: null,
      deletedAt: null,
    },
    isConfirmed: true,
    isCancelled: false,
    isNoShow: false,
    isRescheduled: false,
    createdAt: dayjs(),
    updatedAt: null,
    deletedAt: null,
  },
  {
    id: 3,
    datetime: dayjs(),
    realStartDatetime: null,
    client: {
      id: 3,
      fullname: 'Maria de Lurdes',
      phoneNumber: '11985531444',
      createdAt: dayjs(),
      updatedAt: null,
      deletedAt: null,
    },
    procedure: {
      id: 1,
      name: 'Brow Lamination',
      priceInCents: 10000,
    },
    coupon: null,
    discountPercent: null,
    isConfirmed: true,
    isCancelled: false,
    isNoShow: false,
    isRescheduled: false,
    createdAt: dayjs(),
    updatedAt: null,
    deletedAt: null,
  }
];